#!/bin/sh
# generate self signed ssl cert only if all cert files are empty or nonexistent


if [ -s /etc/ssl/mosquitto.crt.pem ] || [ -n "${SKIP_SSL_GENERATE}" ]; then
    echo "Skipping SSL certificate generation"
else
    mkdir -p /etc/ssl
    cd /etc/ssl

    # taken from https://docs.docker.com/engine/swarm/secrets/#intermediate-example-use-secrets-with-a-nginx-service

    echo "First generating ca certificate"

    openssl genrsa -out "root-ca.key" 4096

    openssl req \
        -new -key "root-ca.key" \
        -out "root-ca.csr" -sha256 \
        -subj '/CN=Mosquitto Root CA'

    openssl x509 -req  -days 3650  -in "root-ca.csr" \
        -signkey "root-ca.key" -sha256 -out "root-ca.crt.pem" \
        -extfile "root-ca.cnf" -extensions \
        root_ca

    echo "Now generating mosquitto certificates"

    openssl genrsa -out "mosquitto.key.pem" 4096

    openssl req -new -key "mosquitto.key.pem" -out "mosquitto.csr" -sha256 \
        -subj "/CN=${CERT_HOSTNAME}"

    openssl x509 -req -days 750 -in "mosquitto.csr" -sha256 \
        -CA "root-ca.crt.pem" -CAkey "root-ca.key"  -CAcreateserial \
        -out "mosquitto.crt.pem" -extfile "site.cnf" -extensions server

fi
